### ISSUE TITLE
There is a bug in intersect_scan, specifically in intersect_two_way.

### ISSUE THREAD

**Issue by igorbologovv** [derivator/box_intersect_ze#2]
To reproduce:

```rust
#[test]
    fn box_intersect_2() {
        let mut boxes = set::BBoxSet::<boxes::Box2Df32, usize>::with_capacity(3);
        let b1 = boxes::Box2Df32::new([0.11,0.2], [0.2, 0.3]);
        let b2 = boxes::Box2Df32::new([0.11,0.11], [0.19, 0.18]);
        boxes.push(1, b1);
        boxes.push(2, b2);

        let mut result = Vec::with_capacity(boxes.len());
        intersect_brute_force::<_, _>(&boxes, &boxes, &mut result);
        assert_eq!(result, []); // passes
        intersect_scan::<_, _>(&boxes, &boxes, &mut result);
        assert_eq!(result, []); // passes

        let mut boxes1 = set::BBoxSet::<boxes::Box2Df32, usize>::with_capacity(3);
        boxes1.push(1,b1);
        let mut boxes2 = set::BBoxSet::<boxes::Box2Df32, usize>::with_capacity(3);
        boxes2.push(usize::MAX-1,b2);
        intersect_brute_force::<_, _>(&boxes1, &boxes2, &mut result);
        assert_eq!(result, []); // passes
        intersect_scan::<_, _>(&boxes1, &boxes2, &mut result);
        assert_eq!(result, []); // fails
    }
```

Apparently the trigger is two boxes which overlap in first dimension but not in second. Apparently only scan intersect is affected.

**Comment by derivator** [comment]
Thanks for reporting this! I believe I have found the problem: the `max_dim_check` parameter is not applied correctly for the two way scan. Additionally, the test data is faulty due to a bug in `random_boxes`: `boxes2` in `test_data` contains no boxes at all, that's why the tests didn't catch this bug.

**Comment by alexpyattaev** [comment]
Can you give any guidance as to what specifically the problem may be? The code is pretty involved, so it is tough to figure out what could be going wrong there. Hopefully we could help fix this.

**Comment by derivator** [comment]
Compare how `max_dim_check` is applied in [`one_way_scan`](https://github.com/derivator/box_intersect_ze/blob/92c3733863e435ceabf16f3bda986abbedfe76e8/src/internals.rs#L54) and [`_two_way_scan`](https://github.com/derivator/box_intersect_ze/blob/92c3733863e435ceabf16f3bda986abbedfe76e8/src/internals.rs#L128). The tests pass if we change the range in the latter to `1..=max_dim_check`. However, the `simulated_one_way_scan` works either way, presumably because the highest dimension is already checked if `SIMULATE_ONE_WAY==true`. The fix seems very straightforward, change to `1..=max_dim_check` for the `SIMULATE_ONE_WAY==false` case, but I want to familiarize myself with the paper again a bit before I push something, just in case I'm missing something.

**Comment by alexpyattaev** [comment]
Thanks! We might find some time next week to try some things, if we manage
tobfix this we will make a pr.


pe 19. toukok. 2023 klo 23.32 derivator ***@***.***>
kirjoitti:

**Comment by derivator** [comment]
I've finally had time to think about this some more and have fixed the bug. As I already suspected, `simulated_one_way_scan` can skip the intersection check for the highest dimension, because it checks for a stricter criterion. The `two_way_scan` case does not do that stricter check, and so had to be adjusted to do the regular intersection check after all.

**Comment by alexpyattaev** [comment]
Thanks! We will do tests on our side and let you know if anything strange surfaces.
